name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

# Only report errors/warnings with codes:

# E9: Syntax errors, indentation errors, and other Python parse errors
# F63: Issues with “comparison with is literals” and others (e.g., F631)
# F7: Errors related to misplaced or undefined variables (e.g., F701)
# F82: Variable assignment before definition, undefined or unused variables (It skips all other error/warning codes!)

    # OPTIONAL: Run tests if you add them
    # - name: Run tests with pytest
    #   run: |
    #     pip install pytest
    #     pytest tests/

    - name: Build Docker image
      run: |
        docker build -t house_price_predictor -f api/Dockerfile .


    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag Docker image
      run: |
        docker tag house_price_predictor ${{ secrets.DOCKERHUB_USERNAME }}/house_price_predictor:latest

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/house_price_predictor:latest
